name: CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v4
      with:
        path: build/DerivedData
        key: ${{ runner.os }}-dataloader-dd
    - name: Build and Test
      run: ci/run.sh
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
